name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev

jobs:

  deploy-staging:
    if: endsWith(github.ref, 'dev') == true
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - run: |
          echo DEPLOY STAGING 

  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    if: endsWith(github.ref, 'main') == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.semantic-release-bot }}
      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.test_semantic_token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release

  deploy-prod:
    needs: release
    permissions:
      id-token: write
      contents: read
    if: endsWith(github.ref, 'main') == true
    runs-on: ubuntu-lst
    timeout-minutes: 3
    steps:
      - run: |
          echo DEPLOY STAGING 

#  deploy-prod:
#    needs: release
#    permissions:
#      id-token: write
#      contents: read
#    if: endsWith(github.ref, 'main') == true
#    runs-on: ubuntu-lst
#    timeout-minutes: 15
#    steps:
#      - name: configure AWS creds
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-region: eu-west-3
#          role-to-assume: arn:aws:iam::931045011413:role/GithubRoleAccesForDeploy
#          role-session-name: github-actions-session
#      - name: Start CodePipeline
#        uses: moia-oss/aws-codepipeline-trigger@v1
#        with:
#          pipeline: falco-pipeline
#          wait: false
#          follow-codebuild: false
#      - run: |
#          echo The PR was merged


# ##

#name: CI/CD Pipeline
#
#on:
#  push:
#    branches:
#      - dev
#      - main
#  pull_request:
#    branches:
#      - dev
#
#jobs:
#  release:
#    name: Release
#    runs-on: ubuntu-latest
#    permissions:
#      contents: write
#      issues: write
#      pull-requests: write
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Install dependencies
#        run: pip install -r requirements.txt
#
#      - name: Install semantic-release extra plugins
#        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
#
#      - name: Release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
#        run: npx semantic-release
#
#  test:
#    if: endsWith(github.ref, 'devel') == true
#    runs-on: ubuntu-latest
#    steps:
#      - run: |
#          echo The PR was merged
