name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: setup semantic-release
        # run: npm install -g semantic-release @semantic-release/git
        run: npx -p node@v18-lts -c "npx semantic-release"

      - name: Run Semantic Release
        run: semantic-release
