name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
        
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      # - name: setup semantic-release
        # run: npm install -g semantic-release @semantic-release/git
        # run: npx -p node@v18-lts -c "npx semantic-release"
        
      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git    

      # - name: Run Semantic Release
       # run: semantic-release
        
      # - name: Build
        # run: npm run build      
        
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
        
